name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Executable
        run: |
          pyinstaller --onefile --name email_sender app.py
        shell: bash

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: email_sender-${{ matrix.os }}
          path: dist/email_sender*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Ubuntu Executable
        uses: actions/download-artifact@v3
        with:
          name: email_sender-ubuntu-latest

      - name: Download Windows Executable
        uses: actions/download-artifact@v3
        with:
          name: email_sender-windows-latest

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

